import { defineConfig } from "vitepress";

// takoform.com — the API and common-model-only site this repository owns.
//
// What is served here is the frozen normative Host API v1/common-model
// closure, non-normative indexes and presentation, the exact public schema
// bytes at the paths their $id names, and conformance language. Form
// definitions, per-Form examples, publisher
// catalogs, and client adapter pages are not served here; each belongs to the
// publisher or adapter that owns it.
//
// Pages under /spec/ and every file under public/schemas/ are generated by
// scripts/site.mjs and checked byte-for-byte by `bun run check:site`. A /spec/
// mirror is normative only when v1.freeze.json lists its source; the overview,
// navigation, and schema-index mirrors explicitly say they are non-normative.

const repository = "https://github.com/tako0614/takoform";

const contractSidebar = [
  {
    text: "Contract map",
    items: [
      { text: "Overview", link: "/spec/" },
      { text: "Conformance language", link: "/spec/conformance" },
      { text: "Versioning and compatibility", link: "/spec/versioning" },
      { text: "Portability boundary", link: "/spec/portability-boundary" },
    ],
  },
  {
    text: "Host API v1",
    items: [
      { text: "Lane overview", link: "/spec/host-api/" },
      { text: "Wire contract", link: "/spec/host-api/v1" },
    ],
  },
  {
    text: "Common model",
    items: [
      { text: "Form Definition", link: "/spec/form-definition/" },
      { text: "Form Package", link: "/spec/form-package/" },
      { text: "Immutable Snapshot", link: "/spec/core/" },
      { text: "Form families", link: "/spec/form-families" },
    ],
  },
  {
    text: "Digest-bound contracts",
    items: [
      { text: "Interface contract", link: "/spec/interface-contract/" },
      { text: "Binding contract", link: "/spec/binding-contract/" },
      { text: "Artifact transport", link: "/spec/artifact-transport/" },
      { text: "Standard services", link: "/spec/standard-services/" },
      { text: "Trust and revocation", link: "/spec/trust/" },
      { text: "Schema identity index", link: "/spec/schemas/" },
    ],
  },
];

const guideSidebar = [
  {
    text: "読む順番",
    items: [
      { text: "Host API v1 とは", link: "/host-api/" },
      { text: "共通モデル", link: "/model/" },
      { text: "conformance と参照実装", link: "/conformance/" },
    ],
  },
  {
    text: "machine contract",
    items: [{ text: "公開 schema", link: "/schemas/" }],
  },
  {
    text: "この site",
    items: [{ text: "所有と公開", link: "/site" }],
  },
];

export default defineConfig({
  lang: "ja-JP",
  title: "Takoform",
  description:
    "Takoform Host API v1 と publisher 中立な共通モデルの normative 契約、公開 schema、conformance。",
  cleanUrls: true,
  lastUpdated: false,
  // VitePress 1.6 builds the local-search MiniSearch index through a concurrent
  // mapper. MiniSearch assigns numeric document IDs in completion order, so a
  // concurrency greater than one changes content-hashed asset names between
  // otherwise identical builds. This small site values reproducible release
  // bytes over parallel rendering.
  buildConcurrency: 1,
  // Every schema URL below resolves to a file the build copies verbatim out of
  // public/, not to a page, so the page-route link checker cannot see it. The
  // bytes at those paths are proved separately, and far more strictly, by
  // scripts/site.mjs against the append-only identity ledger.
  ignoreDeadLinks: [/^\/schemas\/.+\.json$/u, /^\/\.well-known\//u],
  sitemap: {
    hostname: "https://takoform.com",
    transformItems: (items) =>
      items.filter((item) => item.url !== "404.html" && !item.url.endsWith("/404.html")),
  },
  // The pinned vite/esbuild pair below cannot downlevel destructuring to the
  // default browser target list. Nothing here needs to run on a 2021 browser,
  // and building for one silently costs the pin.
  vite: {
    build: { target: "esnext", chunkSizeWarningLimit: 700 },
  },
  head: [
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Takoform" }],
    ["meta", { name: "color-scheme", content: "light dark" }],
  ],
  themeConfig: {
    outline: { level: [2, 3] },
    search: { provider: "local" },
    nav: [
      { text: "Host API v1", link: "/host-api/" },
      { text: "API と概念", link: "/spec/" },
      { text: "schema", link: "/schemas/" },
      { text: "GitHub", link: repository },
    ],
    sidebar: {
      "/spec/": contractSidebar,
      "/": guideSidebar,
    },
    socialLinks: [{ icon: "github", link: repository }],
    footer: {
      message:
        'normative source は <a href="https://github.com/tako0614/takoform">tako0614/takoform</a>。realized DNS と配信 account は公開 operator の authority です。',
      copyright: "MIT © 2026 Takoform contributors",
    },
    docFooter: { prev: "前へ", next: "次へ" },
    darkModeSwitchLabel: "配色",
    returnToTopLabel: "先頭へ",
    sidebarMenuLabel: "目次",
    outlineTitle: "このページ",
    notFound: {
      title: "ページがありません",
      quote: "この site は Host API v1 と共通モデルだけを配信します。",
      linkText: "トップへ",
    },
  },
  // The mirrored specification prose and non-normative indexes are authored
  // in English while the site chrome and guides are Japanese. Declaring one
  // language for both would mislabel roughly half the pages, so the mirrored
  // tree states its own.
  transformHtml(code, _id, context) {
    if (!context.pageData.relativePath.startsWith("spec/")) return code;
    return code.replace(/<html([^>]*)\slang="ja-JP"/u, '<html$1 lang="en"');
  },
});
