import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { defineConfig, type DefaultTheme } from "vitepress";
import { renderForSearch } from "./search.mjs";
import { fileURLToPath } from "node:url";

const configDirectory = path.dirname(fileURLToPath(import.meta.url));

// Pages rarely carry a frontmatter description. Fall back to the first prose
// paragraph of the Markdown source so a shared link describes the actual page
// rather than repeating the site blurb.
function firstParagraph(srcDir, relativePath) {
  try {
    const raw = readFileSync(path.join(srcDir, relativePath), "utf8");
    const body = raw.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "");
    for (const line of body.split("\n")) {
      const text = line.trim();
      if (
        text === "" ||
        text.startsWith("#") ||
        text.startsWith("<") ||
        text.startsWith("```") ||
        text.startsWith("---") ||
        text.startsWith(":::") ||
        text.startsWith("|")
      )
        continue;
      const plain = text
        .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
        .replace(/<[^>]+>/g, "")
        .replace(/\{#[^}]+\}/g, "")
        .replace(/[*_`~]/g, "")
        .replace(/\s+/g, " ")
        .trim();
      if (plain !== "") return plain.slice(0, 200);
    }
  } catch {
    // Fall back to the site-level description below.
  }
  return undefined;
}

// takoform.com — the API and common-model-only site this repository owns.
//
// A local build carries the frozen normative Host API v1/common-model closure,
// the published, fixed English Host API v2 contract, non-normative indexes and
// presentation, the exact public schema bytes at the paths their $id names,
// and conformance language.
// Published Form definitions, family-specific examples, publisher
// catalogs, and third-party client adapter pages are not served here; each belongs to the
// publisher or adapter that owns it.
//
// Pages under /spec/ and every file under public/schemas/ are generated by
// scripts/site.mjs and checked byte-for-byte by `bun run check:site`. A /spec/
// v1 mirror is normative only when v1.freeze.json lists its source. V2 mirrors
// declare authority and version status separately; navigation and indexes
// are non-normative.

const repository = "https://github.com/tako0614/takoform";
// The pinned esbuild 0.28 pair cannot downlevel object/array destructuring
// during dependency pre-bundling. Keep the browser build target independent:
// this only applies to Vite's development optimizer, not the release build.
const DEV_OPTIMIZE_TARGET = "esnext";
const BUILD_TARGET = "esnext";

const contractSidebar = [
  {
    text: "Contract map",
    items: [
      { text: "Conformance language", link: "/spec/conformance" },
      { text: "Versioning and compatibility", link: "/spec/versioning" },
      { text: "Portability boundary", link: "/spec/portability-boundary" },
    ],
  },
  {
    text: "API specification",
    items: [
      { text: "Wire contract", link: "/spec/host-api/v1" },
    ],
  },
  {
    text: "Common model",
    items: [
      { text: "Form Definition", link: "/spec/form-definition/" },
      { text: "Form Package", link: "/spec/form-package/" },
      { text: "Immutable Snapshot", link: "/spec/core/" },
      { text: "Form families", link: "/spec/form-families" },
    ],
  },
  {
    text: "Digest-bound contracts",
    items: [
      { text: "Interface contract", link: "/spec/interface-contract/" },
      { text: "Binding contract", link: "/spec/binding-contract/" },
      { text: "Artifact transport", link: "/spec/artifact-transport/" },
      { text: "Standard services", link: "/spec/standard-services/" },
      { text: "Trust and revocation", link: "/spec/trust/" },
      { text: "Schema identity index", link: "/spec/schemas/" },
    ],
  },
];

const v2Sidebar = [
  { text: "Host API v2", link: "/v2/" },
  {
    text: "Host API v2",
    items: [
      { text: "Overview", link: "/spec/host-api/v2/" },
      { text: "HTTP API", link: "/spec/host-api/v2/http" },
      { text: "Form requirements", link: "/spec/host-api/v2/forms" },
      { text: "Examples", link: "/spec/host-api/v2/examples" },
      { text: "Migration from v1", link: "/spec/host-api/v2/migration" },
    ],
  },
  {
    text: "Guides",
    items: [
      { text: "Getting started", link: "/start/" },
      { text: "Common model", link: "/model/" },
      { text: "Client design", link: "/client/" },
      { text: "Create a Form", link: "/authoring/" },
      { text: "Using v2", link: "/use/" },
      { text: "Implementing a Host", link: "/host-api/" },
      { text: "Implementation guides", link: "/guides/" },
      { text: "Glossary", link: "/glossary" },
    ],
  },
];

const v1Sidebar = [
  { text: "Host API v1", link: "/v1/" },
  { text: "Conformance checks", link: "/conformance/" },
  { text: "Public schemas", link: "/schemas/" },
  ...contractSidebar,
];

// Page names stay English in both locales; only their content routes differ.
function englishSidebar(items: DefaultTheme.SidebarItem[]): DefaultTheme.SidebarItem[] {
  return items.map((item) => ({
    ...item,
    ...(item.link ? { link: `/en${item.link}` } : {}),
    ...(item.items ? { items: englishSidebar(item.items) } : {}),
  }));
}

function collectSidebarLinks(items: DefaultTheme.SidebarItem[]): string[] {
  return items.flatMap((item) => [
    ...(item.link ? [item.link] : []),
    ...(item.items ? collectSidebarLinks(item.items) : []),
  ]);
}

const v1SpecSidebarRoutes = [...new Set(
  collectSidebarLinks(v1Sidebar)
    .filter((link) => link.startsWith("/spec/"))
    .filter((link) => link !== "/spec/" && link !== "/spec/host-api/")
    .map((link) => link.replace(/\/+$/u, "")),
)];

const rootSpecSidebars = {
  "/spec": [],
  "/spec/host-api": [],
  "/spec/host-api/v2": v2Sidebar,
  ...Object.fromEntries(v1SpecSidebarRoutes.map((route) => [route, v1Sidebar])),
};

const englishSpecSidebars = {
  "/en/spec": [],
  "/en/spec/host-api": [],
  "/en/spec/host-api/v2": englishSidebar(v2Sidebar),
  ...Object.fromEntries(v1SpecSidebarRoutes.map((route) => [
    `/en${route}`,
    englishSidebar(v1Sidebar),
  ])),
};

export default defineConfig({
  lang: "ja-JP",
  title: "Takoform",
  description:
    "仕様をURLで公開し、対応するサーバーでリソースを管理するための共通API。",
  locales: {
    root: { label: "日本語", lang: "ja-JP" },
    en: {
      label: "English",
      lang: "en",
      description: "A common API for managing resources on servers that implement a specification published at a URL.",
      themeConfig: {
        nav: [
          { text: "Overview", link: "/en/" },
        ],
        sidebar: {
          ...englishSpecSidebars,
          "/en/v2/": englishSidebar(v2Sidebar),
          "/en/start/": englishSidebar(v2Sidebar),
          "/en/model/": englishSidebar(v2Sidebar),
          "/en/client/": englishSidebar(v2Sidebar),
          "/en/authoring/": englishSidebar(v2Sidebar),
          "/en/use/": englishSidebar(v2Sidebar),
          "/en/host-api/": englishSidebar(v2Sidebar),
          "/en/guides/": englishSidebar(v2Sidebar),
          "/en/glossary": englishSidebar(v2Sidebar),
          "/en/conformance/": englishSidebar(v1Sidebar),
          "/en/schemas/": englishSidebar(v1Sidebar),
          "/en/v1/": englishSidebar(v1Sidebar),
          "/en/site": [],
          "/": [],
        },
        footer: {
          message: '<a href="/en/site">About this site</a> · <a href="https://github.com/tako0614/takoform">GitHub</a>',
          copyright: "MIT © 2026 Takoform contributors",
        },
        docFooter: { prev: "Previous page", next: "Next page" },
        darkModeSwitchLabel: "Appearance", returnToTopLabel: "Return to top",
        sidebarMenuLabel: "Menu", outlineTitle: "On this page",
        langMenuLabel: "Change language",
        notFound: { title: "Page not found", quote: "Check the URL or use search to find a page.", linkText: "Home" },
      },
    },
  },
  cleanUrls: true,
  lastUpdated: false,
  markdown: {
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  // VitePress 1.6 builds the local-search MiniSearch index through a concurrent
  // mapper. MiniSearch assigns numeric document IDs in completion order, so a
  // concurrency greater than one changes content-hashed asset names between
  // otherwise identical builds. This small site values reproducible release
  // bytes over parallel rendering.
  buildConcurrency: 1,
  // Every schema URL below resolves to a file the build copies verbatim out of
  // public/, not to a page, so the page-route link checker cannot see it. The
  // bytes at those paths are proved separately, and far more strictly, by
  // scripts/site.mjs against the append-only identity ledger.
  ignoreDeadLinks: [/^\/schemas\/.+\.json$/u, /^\/\.well-known\//u],
  sitemap: {
    hostname: "https://takoform.com",
    transformItems: (items) =>
      items.filter((item) => item.url !== "404.html" && !item.url.endsWith("/404.html")),
  },
  // The pinned vite/esbuild pair below cannot downlevel destructuring to the
  // default browser target list. Nothing here needs to run on a 2021 browser,
  // and building for one silently costs the pin.
  vite: {
    resolve: {
      alias: [
        {
          find: /^\.\/VPLocalSearchBox\.vue$/u,
          replacement: path.resolve(
            configDirectory,
            "theme/components/VersionSearch.vue",
          ),
        },
      ],
    },
    optimizeDeps: {
      esbuildOptions: { target: DEV_OPTIMIZE_TARGET },
    },
    build: { target: BUILD_TARGET, chunkSizeWarningLimit: 700 },
  },
  head: [
    ["meta", { name: "adring-site-verification", content: "adring_vrf_EyXa-BuHjAKcQYWnxeap4odKOxDj5svQ" }],
    ["link", { rel: "icon", href: "data:," }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Takoform" }],
    ["meta", { name: "twitter:card", content: "summary" }],
    ["meta", { name: "color-scheme", content: "light dark" }],
  ],
  transformHead({ pageData, siteConfig, title, description }) {
    const route = pageData.relativePath
      .replace(/(^|\/)index\.md$/u, "$1")
      .replace(/\.md$/u, "");
    const ogDescription = pageData.frontmatter?.description
      ? description
      : (siteConfig?.srcDir
          ? firstParagraph(siteConfig.srcDir, pageData.relativePath)
          : undefined) ?? description;
    const pageUrl = new URL(route, "https://takoform.com/").href;
    // hreflang targets the same page in the other locale when that source file
    // exists; x-default points at the root (Japanese) locale.
    const jaPath = pageData.relativePath.startsWith("en/")
      ? pageData.relativePath.slice(3)
      : pageData.relativePath;
    const jaRoute = jaPath
      .replace(/(^|\/)index\.md$/u, "$1")
      .replace(/\.md$/u, "");
    const hasJa =
      siteConfig?.srcDir !== undefined &&
      existsSync(path.join(siteConfig.srcDir, jaPath));
    const hasEn =
      siteConfig?.srcDir !== undefined &&
      existsSync(path.join(siteConfig.srcDir, `en/${jaPath}`));
    const jaUrl = new URL(jaRoute, "https://takoform.com/").href;
    const enUrl = new URL(`en/${jaRoute}`, "https://takoform.com/").href;
    const alternates = [];
    if (hasJa) {
      alternates.push(["link", { rel: "alternate", hreflang: "ja", href: jaUrl }]);
    }
    if (hasEn) {
      alternates.push(["link", { rel: "alternate", hreflang: "en", href: enUrl }]);
    }
    if (hasJa && hasEn) {
      alternates.push(["link", { rel: "alternate", hreflang: "x-default", href: jaUrl }]);
    }
    return [
      ["meta", { property: "og:title", content: title }],
      ["meta", { property: "og:description", content: ogDescription }],
      ["meta", { property: "og:locale", content: route.startsWith("en/") ? "en_US" : "ja_JP" }],
      ["meta", { property: "og:url", content: pageUrl }],
      ["link", { rel: "canonical", href: pageUrl }],
      ...alternates,
      ["meta", { name: "twitter:title", content: title }],
      ["meta", { name: "twitter:description", content: ogDescription }],
    ];
  },
  themeConfig: {
    outline: { level: [2, 3] },
    search: { provider: "local", options: { _render: renderForSearch, locales: { root: { translations: {
      button: { buttonText: "検索", buttonAriaLabel: "検索" },
      modal: {
        displayDetails: "詳細を表示", resetButtonTitle: "検索をクリア",
        backButtonTitle: "閉じる", noResultsText: "見つかりませんでした",
        footer: { selectText: "選択", navigateText: "移動", closeText: "閉じる" },
      },
    } } } } },
    nav: [
      { text: "Overview", link: "/" },
    ],
    sidebar: {
      ...rootSpecSidebars,
      "/v2/": v2Sidebar,
      "/start/": v2Sidebar,
      "/model/": v2Sidebar,
      "/client/": v2Sidebar,
      "/authoring/": v2Sidebar,
      "/use/": v2Sidebar,
      "/host-api/": v2Sidebar,
      "/guides/": v2Sidebar,
      "/glossary": v2Sidebar,
      "/v1/": v1Sidebar,
      "/conformance/": v1Sidebar,
      "/schemas/": v1Sidebar,
      "/site": [],
      "/": [],
    },
    socialLinks: [{ icon: "github", link: repository }],
    footer: {
      message:
        '<a href="/site">このサイトについて</a> · <a href="https://github.com/tako0614/takoform">GitHub</a>',
      copyright: "MIT © 2026 Takoform contributors",
    },
    docFooter: { prev: "前へ", next: "次へ" },
    darkModeSwitchLabel: "配色",
    returnToTopLabel: "先頭へ",
    sidebarMenuLabel: "目次",
    outlineTitle: "このページ",
    langMenuLabel: "言語を切り替える",
    notFound: {
      title: "ページがありません",
      quote: "URLが正しいか確認するか、検索から探してください。",
      linkText: "トップへ",
    },
  },
  // The document follows its locale on both SSR and client navigation.
  // Generated specification bodies declare lang="en" independently.
  transformHtml(code, _id, context) {
    const authority = context.pageData.frontmatter.normative === true
      ? "normative"
      : "non-normative";
    return code.replace(
      /<html\b/u,
      `<html data-document-authority="${authority}"`,
    );
  },
});
