import { defineConfig, type DefaultTheme } from "vitepress";
import { renderForSearch } from "./search.mjs";

// takoform.com — the API and common-model-only site this repository owns.
//
// What is served here is the frozen normative Host API v1/common-model
// closure, non-normative indexes and presentation, the exact public schema
// bytes at the paths their $id names, and conformance language. Published Form
// definitions, family-specific examples, publisher
// catalogs, and third-party client adapter pages are not served here; each belongs to the
// publisher or adapter that owns it.
//
// Pages under /spec/ and every file under public/schemas/ are generated by
// scripts/site.mjs and checked byte-for-byte by `bun run check:site`. A /spec/
// mirror is normative only when v1.freeze.json lists its source; the overview,
// navigation, and schema-index mirrors explicitly say they are non-normative.

const repository = "https://github.com/tako0614/takoform";

// The pinned esbuild 0.28 pair cannot downlevel object/array destructuring
// during dependency pre-bundling. Keep the browser build target independent:
// this only applies to Vite's development optimizer, not the release build.
const DEV_OPTIMIZE_TARGET = "esnext";
const BUILD_TARGET = "esnext";

const contractSidebar = [
  {
    text: "Contract map",
    items: [
      { text: "Overview", link: "/spec/" },
      { text: "Conformance language", link: "/spec/conformance" },
      { text: "Versioning and compatibility", link: "/spec/versioning" },
      { text: "Portability boundary", link: "/spec/portability-boundary" },
    ],
  },
  {
    text: "Host API v1",
    items: [
      { text: "Lane overview", link: "/spec/host-api/" },
      { text: "Wire contract", link: "/spec/host-api/v1" },
    ],
  },
  {
    text: "Common model",
    items: [
      { text: "Form Definition", link: "/spec/form-definition/" },
      { text: "Form Package", link: "/spec/form-package/" },
      { text: "Immutable Snapshot", link: "/spec/core/" },
      { text: "Form families", link: "/spec/form-families" },
    ],
  },
  {
    text: "Digest-bound contracts",
    items: [
      { text: "Interface contract", link: "/spec/interface-contract/" },
      { text: "Binding contract", link: "/spec/binding-contract/" },
      { text: "Artifact transport", link: "/spec/artifact-transport/" },
      { text: "Standard services", link: "/spec/standard-services/" },
      { text: "Trust and revocation", link: "/spec/trust/" },
      { text: "Schema identity index", link: "/spec/schemas/" },
    ],
  },
];

const guideSidebar = [
  { text: "トップ", link: "/" },
  {
    text: "ドキュメント",
    items: [
      { text: "はじめる", link: "/start/" },
      { text: "実装ガイド", link: "/guides/" },
      { text: "Formを作る", link: "/authoring/" },
      { text: "GoからHostを使う", link: "/client/" },
      { text: "仕様一覧", link: "/reference/" },
      { text: "用語集", link: "/glossary" },
      { text: "Host API v1 とは", link: "/host-api/" },
      { text: "共通モデル", link: "/model/" },
      { text: "適合性の検証", link: "/conformance/" },
    ],
  },
  {
    text: "JSON Schema",
    items: [{ text: "スキーマ一覧", link: "/schemas/" }],
  },
  {
    text: "サイト情報",
    items: [{ text: "このサイトについて", link: "/site" }],
  },
];

const englishLabels: Record<string, string> = {
  トップ: "Home", ドキュメント: "Documentation", はじめる: "Getting started",
  実装ガイド: "Implementation guides", 仕様一覧: "Reference", 用語集: "Glossary",
  Formを作る: "Create a Form", GoからHostを使う: "Use a Host from Go",
  "Host API v1 とは": "About Host API v1", 共通モデル: "Common model",
  適合性の検証: "Conformance checks", スキーマ一覧: "Schema index",
  サイト情報: "Site information", このサイトについて: "About this site",
};

function englishSidebar(items: DefaultTheme.SidebarItem[]): DefaultTheme.SidebarItem[] {
  return items.map((item) => ({
    ...item,
    text: englishLabels[item.text ?? ""] ?? item.text,
    ...(item.link ? { link: `/en${item.link}` } : {}),
    ...(item.items ? { items: englishSidebar(item.items) } : {}),
  }));
}

const relatedSidebar = {
  text: "関連リンク",
  items: [
    { text: "Edge Forms", link: "https://edge.forms.takoform.com/" },
    { text: "GitHub", link: repository },
  ],
};

export default defineConfig({
  lang: "ja-JP",
  title: "Takoform",
  description:
    "リソースの定義、検証、管理APIのための仕様とGoライブラリ。",
  locales: {
    root: { label: "日本語", lang: "ja-JP" },
    en: {
      label: "English",
      lang: "en",
      description: "Specifications and Go libraries for resource definitions, verification and management APIs.",
      themeConfig: {
        nav: [
          { text: "Start", link: "/en/start/" },
          { text: "Guides", link: "/en/guides/" },
          { text: "Reference", link: "/en/reference/" },
          { text: "Glossary", link: "/en/glossary" },
          { text: "GitHub", link: repository },
        ],
        sidebar: [
          ...englishSidebar([...guideSidebar, ...contractSidebar]),
          { ...relatedSidebar, text: "Related links", items: [
            { text: "Edge Forms", link: "https://edge.forms.takoform.com/" },
            { text: "GitHub", link: repository },
          ] },
        ],
        footer: {
          message: 'Specifications and source code are available on <a href="https://github.com/tako0614/takoform">GitHub</a>.',
          copyright: "MIT © 2026 Takoform contributors",
        },
        docFooter: { prev: "Previous page", next: "Next page" },
        darkModeSwitchLabel: "Appearance", returnToTopLabel: "Return to top",
        sidebarMenuLabel: "Menu", outlineTitle: "On this page",
        langMenuLabel: "Change language",
        notFound: { title: "Page not found", quote: "Check the URL or use search to find a page.", linkText: "Home" },
      },
    },
  },
  cleanUrls: true,
  lastUpdated: false,
  markdown: {
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  // VitePress 1.6 builds the local-search MiniSearch index through a concurrent
  // mapper. MiniSearch assigns numeric document IDs in completion order, so a
  // concurrency greater than one changes content-hashed asset names between
  // otherwise identical builds. This small site values reproducible release
  // bytes over parallel rendering.
  buildConcurrency: 1,
  // Every schema URL below resolves to a file the build copies verbatim out of
  // public/, not to a page, so the page-route link checker cannot see it. The
  // bytes at those paths are proved separately, and far more strictly, by
  // scripts/site.mjs against the append-only identity ledger.
  ignoreDeadLinks: [/^\/schemas\/.+\.json$/u, /^\/\.well-known\//u],
  sitemap: {
    hostname: "https://takoform.com",
    transformItems: (items) =>
      items.filter((item) => item.url !== "404.html" && !item.url.endsWith("/404.html")),
  },
  // The pinned vite/esbuild pair below cannot downlevel destructuring to the
  // default browser target list. Nothing here needs to run on a 2021 browser,
  // and building for one silently costs the pin.
  vite: {
    optimizeDeps: {
      esbuildOptions: { target: DEV_OPTIMIZE_TARGET },
    },
    build: { target: BUILD_TARGET, chunkSizeWarningLimit: 700 },
  },
  head: [
    ["link", { rel: "icon", href: "data:," }],
    ["meta", { property: "og:type", content: "website" }],
    ["meta", { property: "og:site_name", content: "Takoform" }],
    ["meta", { name: "twitter:card", content: "summary" }],
    ["meta", { name: "color-scheme", content: "light dark" }],
  ],
  transformHead({ pageData, title, description }) {
    const route = pageData.relativePath
      .replace(/(^|\/)index\.md$/u, "$1")
      .replace(/\.md$/u, "");
    return [
      ["meta", { property: "og:title", content: title }],
      ["meta", { property: "og:description", content: description }],
      ["meta", { property: "og:url", content: new URL(route, "https://takoform.com/").href }],
      ["meta", { name: "twitter:title", content: title }],
      ["meta", { name: "twitter:description", content: description }],
    ];
  },
  themeConfig: {
    outline: { level: [2, 3] },
    search: { provider: "local", options: { _render: renderForSearch, locales: { root: { translations: {
      button: { buttonText: "検索", buttonAriaLabel: "検索" },
      modal: {
        displayDetails: "詳細を表示", resetButtonTitle: "検索をクリア",
        backButtonTitle: "閉じる", noResultsText: "見つかりませんでした",
        footer: { selectText: "選択", navigateText: "移動", closeText: "閉じる" },
      },
    } } } } },
    nav: [
      { text: "はじめる", link: "/start/" },
      { text: "ガイド", link: "/guides/" },
      { text: "仕様", link: "/reference/" },
      { text: "用語集", link: "/glossary" },
      { text: "GitHub", link: repository },
    ],
    sidebar: [
      ...guideSidebar,
      ...contractSidebar,
      relatedSidebar,
    ],
    socialLinks: [{ icon: "github", link: repository }],
    footer: {
      message:
        '仕様とソースコードは <a href="https://github.com/tako0614/takoform">GitHub</a> で公開しています。',
      copyright: "MIT © 2026 Takoform contributors",
    },
    docFooter: { prev: "前へ", next: "次へ" },
    darkModeSwitchLabel: "配色",
    returnToTopLabel: "先頭へ",
    sidebarMenuLabel: "目次",
    outlineTitle: "このページ",
    langMenuLabel: "言語を切り替える",
    notFound: {
      title: "ページがありません",
      quote: "URLが正しいか確認するか、検索から探してください。",
      linkText: "トップへ",
    },
  },
  // The document follows its locale on both SSR and client navigation.
  // Generated specification bodies declare lang="en" independently.
  transformHtml(code, _id, context) {
    const authority = context.pageData.frontmatter.normative === true
      ? "normative"
      : "non-normative";
    return code.replace(
      /<html\b/u,
      `<html data-document-authority="${authority}"`,
    );
  },
});
